/**
 * Report Generation Service
 *
 * Generates investment reports in various formats.
 * Used by /api/reports/route.ts.
 */

// ─── Types ───────────────────────────────────────────────

export type ReportType = "INVESTMENT" | "WEEKLY_REBALANCE" | "PORTFOLIO_HEALTH";
export type ReportFormat = "PDF" | "MARKDOWN";

export interface ReportData {
  type: ReportType;
  format: ReportFormat;
  recommendationId?: string;
  portfolioData?: {
    totalValueUsd: number;
    riskScore: number;
    assets: Array<{
      tokenSymbol: string;
      tokenName: string;
      allocationPct: number;
      valueUsd: number;
      sector: string;
    }>;
  };
  recommendationData?: {
    decision: string;
    tokenSymbol: string;
    tokenName: string;
    allocation: number;
    confidence: number;
    investmentThesis: string;
  };
}

export interface GeneratedReport {
  id: string;
  type: ReportType;
  format: ReportFormat;
  content: string;
  createdAt: string;
}

// ─── Report Generation ───────────────────────────────────

/**
 * Generate a report based on type and data.
 */
export function generateReport(data: ReportData): GeneratedReport {
  const content = generateMarkdownContent(data);

  return {
    id: `report_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    type: data.type,
    format: data.format,
    content,
    createdAt: new Date().toISOString(),
  };
}

/**
 * Generate markdown content for the report.
 */
function generateMarkdownContent(data: ReportData): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let content = `# Alpha Council Investment Report\n\n`;
  content += `**Generated:** ${date}\n`;
  content += `**Type:** ${formatReportType(data.type)}\n\n`;
  content += `---\n\n`;

  // Portfolio section
  if (data.portfolioData) {
    content += `## Portfolio Overview\n\n`;
    content += `- **Total Value:** $${data.portfolioData.totalValueUsd.toLocaleString()}\n`;
    content += `- **Risk Score:** ${data.portfolioData.riskScore}/100\n\n`;

    content += `### Holdings\n\n`;
    content += `| Asset | Allocation | Value | Sector |\n`;
    content += `|-------|-----------|-------|--------|\n`;
    for (const asset of data.portfolioData.assets) {
      content += `| ${asset.tokenSymbol} | ${(asset.allocationPct * 100).toFixed(1)}% | $${asset.valueUsd.toLocaleString()} | ${asset.sector} |\n`;
    }
    content += `\n`;
  }

  // Recommendation section
  if (data.recommendationData) {
    content += `## Recommendation\n\n`;
    content += `### ${data.recommendationData.decision} ${data.recommendationData.tokenSymbol}\n\n`;
    content += `- **Token:** ${data.recommendationData.tokenName} (${data.recommendationData.tokenSymbol})\n`;
    content += `- **Allocation:** ${data.recommendationData.allocation}%\n`;
    content += `- **Confidence:** ${data.recommendationData.confidence}%\n\n`;
    content += `### Investment Thesis\n\n`;
    content += `${data.recommendationData.investmentThesis}\n\n`;
  }

  // Footer
  content += `---\n\n`;
  content += `*This report was generated by Alpha Council's AI committee. Past performance does not guarantee future results.*\n`;

  return content;
}

function formatReportType(type: ReportType): string {
  switch (type) {
    case "INVESTMENT":
      return "Investment Analysis";
    case "WEEKLY_REBALANCE":
      return "Weekly Rebalance";
    case "PORTFOLIO_HEALTH":
      return "Portfolio Health Check";
  }
}
